server:
  port: 8888
spring:
  application:
    name: app
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 5MB
  profiles:
    include:
      - extend
      - database
logging:
  level:
    root: info