spring:
  datasource:
    url: jdbc:mysql://120.24.95.110:3306/cms?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zd19910404.
entity:
  packages: com._365d1.model
druid:
  username: root
  password: ctb1.2.3.